### ISSUE TITLE
Defer trailing comma rule to prettier

### ISSUE THREAD

**Issue by ismail-syed** [Shopify/stylelint-config-shopify#30]
<img width="689" alt="screen shot 2018-06-18 at 4 09 44 pm" src="https://user-images.githubusercontent.com/6130700/41559474-1b7984fe-7312-11e8-8b83-3ede52659cdc.png">

https://github.com/Shopify/web/pull/4779#discussion_r196194404

**Comment by kaelig** [comment]
FWIW, we ran into a case where we needed the trailing comma (see below), but most of the time we didn't.

https://github.com/Shopify/polaris-styleguide/blob/87221f2bc7edd0173ab8d669ef9cc338ab814681/app/styles/threads/core/_utilities.scss#L57-L61

**Comment by BPScott** [comment]
stylelint has no rule about trailing commas, this issue was due to confusion around old/new versions of prettier.

Closing as this is a non-issue
